#
# lint.yaml
# Created by Perry Naseck on 2022-05-23.
# This file is part of the https://github.com/ABTech/twiki-to-mediawiki-xml
#
# Copyright (C) 2022-present  AB Tech, Carnegie Mellon University
# Copyright (C) 2022          Perry Naseck (git@perrynaseck.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

name: Lint
on: [push, pull_request]

jobs:
  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
  python-lint:
    name: Python lint ${{ matrix.name }} ${{ matrix.python-version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: "3.8",  name: flake8,     cmd: flake8             }
          - { python-version: "3.9",  name: flake8,     cmd: flake8             }
          - { python-version: "3.10", name: flake8,     cmd: flake8             }
          - { python-version: "3.9",  name: pydocstyle, cmd: pydocstyle         }
          - { python-version: "3.8",  name: pylint,     cmd: pylint             }
          - { python-version: "3.9",  name: pylint,     cmd: pylint             }
          - { python-version: "3.10", name: pylint,     cmd: pylint             }
          - { python-version: "3.9",  name: isort,      cmd: isort --check-only }
          - { python-version: "3.9",  name: bandit,     cmd: bandit -r          }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt','**/setup.py','**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-
      - name: Install Python Development Dependencies
        run: python -m pip install -e .[dev]
      - name: Run ${{ matrix.name }}
        run: python -m ${{ matrix.cmd }} twiki_to_mediawiki_xml/
